//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class AthletesNF
    {
        public int IdAthlete { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public Nullable<short> Height { get; set; }
        public Nullable<short> Weight { get; set; }
    }
}
